# ASP.NET Core
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Free Trial(bf321bce-5e0c-48d0-8f5e-e1496482fd22)'
    AuthenticationType: 'server'
    ServerName: 'envuat.database.windows.net'
    DatabaseName: 'bazaUAT'
    SqlUsername: 'malin'
    SqlPassword: 'Malmo.1212'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    IpDetectionMethod: 'AutoDetect'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
trigger:
- master


